/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClassificheRouteImport } from './routes/classifiche'
import { Route as ProRouteImport } from './routes/pro'
import { Route as RegolamentoRouteImport } from './routes/regolamento'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SportRouteImport } from './routes/sport'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as TorneoIdRouteImport } from './routes/torneo.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassificheRoute = ClassificheRouteImport.update({
  id: '/classifiche',
  path: '/classifiche',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const RegolamentoRoute = RegolamentoRouteImport.update({
  id: '/regolamento',
  path: '/regolamento',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SportRoute = SportRouteImport.update({
  id: '/sport',
  path: '/sport',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const TorneoIdRoute = TorneoIdRouteImport.update({
  id: '/torneo/$id',
  path: '/torneo/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/classifiche': typeof ClassificheRoute
  '/pro': typeof ProRoute
  '/regolamento': typeof RegolamentoRoute
  '/settings': typeof SettingsRoute
  '/sport': typeof SportRoute
  '/tournaments': typeof TournamentsRoute
  '/torneo/$id': typeof TorneoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/classifiche': typeof ClassificheRoute
  '/pro': typeof ProRoute
  '/regolamento': typeof RegolamentoRoute
  '/settings': typeof SettingsRoute
  '/sport': typeof SportRoute
  '/tournaments': typeof TournamentsRoute
  '/torneo/$id': typeof TorneoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/classifiche': typeof ClassificheRoute
  '/pro': typeof ProRoute
  '/regolamento': typeof RegolamentoRoute
  '/settings': typeof SettingsRoute
  '/sport': typeof SportRoute
  '/tournaments': typeof TournamentsRoute
  '/torneo/$id': typeof TorneoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/classifiche'
    | '/pro'
    | '/regolamento'
    | '/settings'
    | '/sport'
    | '/tournaments'
    | '/torneo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/classifiche'
    | '/pro'
    | '/regolamento'
    | '/settings'
    | '/sport'
    | '/tournaments'
    | '/torneo/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/classifiche'
    | '/pro'
    | '/regolamento'
    | '/settings'
    | '/sport'
    | '/tournaments'
    | '/torneo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ClassificheRoute: typeof ClassificheRoute
  ProRoute: typeof ProRoute
  RegolamentoRoute: typeof RegolamentoRoute
  SettingsRoute: typeof SettingsRoute
  SportRoute: typeof SportRoute
  TournamentsRoute: typeof TournamentsRoute
  TorneoIdRoute: typeof TorneoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classifiche': {
      id: '/classifiche'
      path: '/classifiche'
      fullPath: '/classifiche'
      preLoaderRoute: typeof ClassificheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regolamento': {
      id: '/regolamento'
      path: '/regolamento'
      fullPath: '/regolamento'
      preLoaderRoute: typeof RegolamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sport': {
      id: '/sport'
      path: '/sport'
      fullPath: '/sport'
      preLoaderRoute: typeof SportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torneo/$id': {
      id: '/torneo/$id'
      path: '/torneo/$id'
      fullPath: '/torneo/$id'
      preLoaderRoute: typeof TorneoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ClassificheRoute: ClassificheRoute,
  ProRoute: ProRoute,
  RegolamentoRoute: RegolamentoRoute,
  SettingsRoute: SettingsRoute,
  SportRoute: SportRoute,
  TournamentsRoute: TournamentsRoute,
  TorneoIdRoute: TorneoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
